version: "3.9"

services:
  postgresdb:
    image: postgres:17.4
    container_name: zentra.db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - zentra_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  zentra_db:
