spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zentra
    username: zentra_user
    password: zentra_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: never
